[package]
name = "strfmt"
version = "0.1.0"
authors = ["PgBiel <https://github.com/PgBiel>"]
license = "MIT"
description = "Convenient Rust-like string formatting in Typst"
entrypoint = "typst-strfmt.typ"
repository = "https://github.com/PgBiel/typst-strfmt"
